//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication15.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Value
    {
        public int ID { get; set; }
        public int PartID { get; set; }
        public int Value1 { get; set; }
        public System.DateTime Date { get; set; }
        public int Clock { get; set; }
    
        public virtual Part Part { get; set; }
    }
}
